version: "3.4"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=postgres
      - PMA_PASSWORD=postgres
  line-bot:
    build:
      context: ./line-bot
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./line-bot:/app
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./discord-bot:/app
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - line-bot
      - discord-bot
networks:
  default:
    external:
      name: ytwatcher

volumes:
  postgres-data: