version: "3.4"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    env_file:
      - .env
    networks:
      - default_network

  db:
    image: mysql:9.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - default_network

  line-bot:
    build:
      context: ./line-bot
      dockerfile: Dockerfile
    volumes:
      - ./line-bot:/app
    networks:
      - default_network

  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    volumes:
      - ./discord-bot:/app
    networks:
      - default_network

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - line-bot
      - discord-bot
    networks:
      - default_network

networks:
  default_network:
    name: ytwatcher
    external: true